### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by gdotten** [Seanba/Tiled2Unity#151]
An item with the same key has already been added.
Exception Stack:    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Tiled2Unity.TsxTileset.<>c__DisplayClass53_0.<FromXml>b__0(TmxTile t)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Tiled2Unity.TsxTileset.FromXml(XElement xml, TmxMap tmxMap)
   at Tiled2Unity.TmxMap.ParseAllTilesets(XDocument doc)
   at Tiled2Unity.TmxMap.ParseMapXml(XDocument doc)
   at Tiled2Unity.TmxMap.LoadFromFile(String tmxPath)
   at Tiled2Unity.Session.LoadTmxFile(String tmxFilePath)

This issue occurs when opening any tiled map file.

**Comment by Seanba** [comment]
Hi there. Can you send me your map and tileset files? There must be something I'm not expecting about those files. (You can find my email at www.seanba.com)

Thanks.
